### ISSUE TITLE
qTrassa-doc?

### ISSUE THREAD

**Issue by zvezdochiot** [neos80/qTrassa#1]
Hi @neos80 .

Сделай `qTrassa-doc`. Можно даже с одним `README.md` и `LICENSE`. Форкну и буду PR-ить туда по возможности. Мне так будет гораздо проще.

**Comment by neos80** [comment]
Отдельную репу? И какую туда лицензию воткнуть? там же документы будут.

**Comment by zvezdochiot** [comment]
Hi @neos80 .

Ежели нет предпочтений, то [The Unlicense](https://github.com/Geo-Linux-Calculations/geofindkey/blob/master/LICENSE).

**Comment by zvezdochiot** [comment]
Hi @neos80 

Отставить! Ты стал участником ORG.GLC. Так что всю шляпу буду катать в https://github.com/Geo-Linux-Calculations/qTrassa/tree/master/doc/circle_concatenate. Доступ у тебя есть.
